db_url = "httpw://192.168.0.200:8086"
db_name = "mqtt2influxdb"
db_user = "root"
db_password = "root"
mqttserverurl = "192.168.0.200"
mqttserverport = 1883
topics = ["sensor1/temp","sensor1/humid","sensor2/temp","sensor2/humid","sensor2/pressure"]
